/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import static org.junit.Assert.*;

import org.junit.Test;

public class AppTest {
  @Test
  public void testAppExists() {
    App classUnderTest = new App();
  }
}
