name: ci-dgraph4j-tests
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches:
      - master
  schedule:
    - cron: "0 0 * * *" # run workflow daily
jobs:
  build:
    name: dgraph4j-tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout dgraph4j repo
        uses: actions/checkout@v4
        with:
          path: dgraph4j
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: microsoft
          java-version-file: dgraph4j/.java-version
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: current
      - name: Checkout Dgraph repo # use latest dgraph build
        uses: actions/checkout@v4
        with:
          path: dgraph
          repository: dgraph-io/dgraph
          ref: main
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: dgraph/go.mod
      - name: Build dgraph binary
        run: cd dgraph && make docker-image # builds docker image with local tag
      - name: Spin up local dgraph cluster
        run: cd dgraph4j && docker compose -f docker-compose.test.yml up -d
      - name: Run tests
        run: cd dgraph4j && gradle build -i
      - name: Tear down cluster
        run: cd dgraph4j && docker compose -f docker-compose.test.yml down
