name: Trunk Code Quality
on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read
  actions: write
  checks: write

jobs:
  trunk-code-quality:
    name: Trunk Code Quality
    uses: dgraph-io/.github/.github/workflows/trunk.yml@main
